doc/_templates/docs-navbar.html, doc/_templates/docs-toc.html, doc/_templates/layout.html, doc/_templates/navbar.html, doc/api.rst, doc/index.rst, doc/whats_new.rst, examples/mne_inverse_envelope_correlation.py, examples/mne_inverse_envelope_correlation_volume.py, mne_connectivity/__init__.py, mne_connectivity/base.py, mne_connectivity/effective.py, mne_connectivity/envelope.py, mne_connectivity/io.py, mne_connectivity/spectral.py, mne_connectivity/tests/test_connectivity.py, mne_connectivity/tests/test_envelope.py, mne_connectivity/tests/test_spectral.py, mne_connectivity/tests/test_utils.py, mne_connectivity/utils/__init__.py, mne_connectivity/viz/_3d.py, mne_connectivity/viz/__init__.py, mne_connectivity/viz/circle.py, requirements.txt, setup.py
PR Description
--------------
Closes: #16 
Closes: #18 
Closes: #10 
- Reading/writing occurs as netCDF files
- Refactoring `combine` in the `envelope_correlation` function into `EpochXXX`
- Allow symmetric RAM optimization
=> [WIP] Enable save/read, simplify "combine" kwarg and allow symmetric RAM optimization

README.rst, mne_connectivity/spectral.py
PR Description
--------------
Describes differences in connectivity measures.
=> [MRG] Adding notes to readme and spectral_connectivity

doc/_templates/navbar.html, doc/_templates/version-switcher.html, doc/authors.inc, doc/conf.py, doc/whats_new.rst, doc/whats_new_previous_releases.rst, mne_connectivity/__init__.py
PR Description
--------------
Closes: #34 
=> [MRG] Adding docs for release

.circleci/config.yml, doc/api.rst, doc/authors.inc, doc/references.bib, doc/whats_new.rst, examples/mne_inverse_envelope_correlation.py, mne_connectivity/__init__.py, mne_connectivity/envelope.py, mne_connectivity/tests/test_envelope.py, mne_connectivity/var.py, requirements_doc.txt, tools/circleci_dependencies.sh
This implements symmetric orthogonalization following https://www.sciencedirect.com/science/article/pii/S1053811915002670.
@agramfort @dengemann @SherazKhan any thoughts on the utility of this versus the already-implemented pairwise orthogonalization? It seems to have the limitation of requiring n_labels < rank, but some advantages mentioned in the paper above (better sensitivity / fewer false alarms among them).
=> ENH: Add symmetric orthogonalization

doc/whats_new.rst, mne_connectivity/base.py, mne_connectivity/envelope.py, mne_connectivity/io.py, mne_connectivity/spectral.py, mne_connectivity/tests/test_connectivity.py, mne_connectivity/tests/test_envelope.py, mne_connectivity/tests/test_spectral.py, requirements.txt
PR Description
--------------
Fixes: #40 
Also fixes complex number writing.
=> [MRG] Fix bug in n_jobs for spectral_connectivity

CONTRIBUTING.md, doc/authors.inc, doc/whats_new.rst, examples/connectivity_classes.py, mne_connectivity/viz/circle.py, tools/circleci_dependencies.sh
PR Description
--------------
Closes #59.
=> [FIX] Change label orientation for upper right quadrant

.github/workflows/unit_tests.yml, doc/api.rst, doc/whats_new.rst, mne_connectivity/base.py, mne_connectivity/conftest.py, mne_connectivity/effective.py, mne_connectivity/envelope.py, mne_connectivity/io.py, mne_connectivity/spectral.py, mne_connectivity/tests/test_connectivity.py, mne_connectivity/utils/__init__.py, mne_connectivity/utils/utils.py, mne_connectivity/vector_ar/tests/test_var.py, mne_connectivity/vector_ar/var.py, mne_connectivity/viz/_3d.py, mne_connectivity/viz/circle.py, requirements.txt, setup.py
PR Description
--------------
Fixes: #51 
I need to have a discussion with MNE about how to best structure the Annotations in a metadata dataframe for downstream usage. Ideally, the data frame facilitates things like searching for Epochs that meet a certain condition or Annotation (i.e. seizure, or `BAD`). 
=> [WIP] Enhance all connectivity containers to store Epoch Annotations

.circleci/config.yml, CITATION.cff, MANIFEST.in, mne_connectivity/envelope.py, mne_connectivity/spectral/epochs.py, mne_connectivity/spectral/time.py, mne_connectivity/tests/test_connectivity.py, mne_connectivity/vector_ar/var.py
PR Description
--------------
See discussion: https://github.com/mne-tools/mne-python/issues/9624
=> Add citation

.github/workflows/unit_tests.yml, mne_connectivity/utils/docs.py, requirements_testing.txt, tools/circleci_dependencies.sh
Let's first see if the CIs replicate the CircleCI failure on MNE-Python `main`
https://app.circleci.com/pipelines/github/mne-tools/mne-python/12447/workflows/f554b29f-0044-448a-98e0-8417a76f2a84/jobs/40711
=> MAINT: Update for latest MNE-Python main

Makefile, doc/conf.py, doc/install.rst, doc/whats_new.rst, doc/whats_new_previous_releases.rst, mne_connectivity/__init__.py, mne_connectivity/io.py, mne_connectivity/tests/test_connectivity.py
PR Description
--------------
Release 0.3.
=> Adding release 0.3

.circleci/config.yml, doc/authors.inc, doc/whats_new.rst, mne_connectivity/spectral/epochs.py, mne_connectivity/spectral/tests/test_spectral.py
PR Description
--------------
Closes: #87
Closes: #92 
In collaboration with [weiglszonja](https://github.com/weiglszonja).
=> [BUG FIX] Fix CircleCI for Fetching and Spectral Connectivity Saving After averaging frequencies

.github/workflows/unit_tests.yml, mne_connectivity/conftest.py, requirements.txt
=> [ENH] Fix CI to use stable

doc/conf.py, examples/dpli_wpli_pli.py, examples/mne_inverse_coherence_epochs.py, examples/mne_inverse_connectivity_spectrum.py, examples/mne_inverse_label_connectivity.py, examples/mne_inverse_psi_visual.py, mne_connectivity/spectral/tests/test_spectral.py, requirements.txt
PR Description
--------------
CI is failing because `data_path()` from MNE-Python used to return str, now it returns PosixPath.
=> [DOC, CI] Fix paths in examples for PosixPath

.github/workflows/unit_tests.yml, doc/authors.inc, doc/whats_new.rst, mne_connectivity/io.py, requirements.txt
PR Description
--------------
closes #109.  There should probably be a test too, but I didn't even see a `tests/test_io.py` file and at the moment I haven't time to do a proper job of *that*.
=> fix for loading with missing event_id

doc/authors.inc, doc/conf.py, doc/whats_new.rst, mne_connectivity/spectral/epochs.py, mne_connectivity/spectral/time.py, mne_connectivity/vector_ar/var.py
PR Description
--------------
Fix https://github.com/mne-tools/mne-connectivity/issues/111
=> add missing @verbose annotations, fix bug#111

.circleci/config.yml, requirements_doc.txt
=> MAINT: Rotate CircleCI key

doc/conf.py, doc/whats_new.rst, mne_connectivity/__init__.py
PR Description
--------------
Closes: #118 
=> [Release] V0.5

doc/whats_new.rst, doc/whats_new_previous_releases.rst, mne_connectivity/__init__.py
=> [v0.6 dev] New version

azure-pipelines.yml, examples/dynamic/README.txt, tools/circleci_dependencies.sh
For https://github.com/mne-tools/mne-python/issues/11532
=> MAINT: Use git

mne_connectivity/spectral/time.py
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)
PR Description
--------------
=> [ENH] Fix doc according to ruuskas comment for mne-python like docstring

.github/workflows/cffconvert.yml
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)
PR Description
--------------
=> [MAINT] Adding citation workflow

.circleci/config.yml, .github/workflows/linux_conda.yml, .github/workflows/unit_tests.yml, .gitignore, codecov.yml, doc/conf.py, ignore_words.txt
I looked quickly at the failures in https://github.com/mne-tools/mne-connectivity/pull/142 and it looks like there is room for updating/optimizing CIs. Will mark for merge when green because these are seemingly straightforward version and action updates that we've taken and used in MNE-Python for some months now.
=> MAINT: Update CIs

mne_connectivity/spectral/time.py
should fix the CI failures that started today
=> avoid FutureWarning from zero_mean default change

doc/_static/versions.json, doc/whats_new.rst, doc/whats_new_previous_releases.rst, examples/compare_coherency_methods.py, pyproject.toml
Would appreciate feedback on the `whats_new` content to make sure everything that should be included is.
~~Will leave as draft until #184 (and possibly #196) are merged.~~ Prerequisites merged.
=> [RELEASE] V0.7

.github/workflows/linux_conda.yml, .github/workflows/unit_tests.yml, doc/install.rst, environment.yml, mne_connectivity/decoding/decomposition.py, mne_connectivity/spectral/epochs.py, mne_connectivity/spectral/epochs_multivariate.py, mne_connectivity/spectral/time.py, mne_connectivity/utils/utils.py, pyproject.toml
Unit tests using Python 3.9 failing since it's no longer supported by MNE, so have just switched these to Python 3.10.
=> [MAINT] Upgrade from Python 3.9 to 3.10

.circleci/config.yml, .github/workflows/linux_conda.yml
https://github.com/mamba-org/setup-micromamba/issues/225
Trying to fix by pinning specific micromamba versions.
=> [MAINT] Fix hanging micromamba in CI

doc/_static/style.css, mne_connectivity/__init__.py
closes #256 
PR Description
--------------
uses correct version; also uses CSS to truncate the really long version hash so it doesn't collide with the menu.
=> fix version on website

azure-pipelines.yml
closes #269 
PR Description
--------------
removes what I think was cruft in the azure pipelines config, left over from when the file was copied / adapted from a similar config for MNE-Python
=> remove crufty conditional
