mne-tools/mne-connectivity

- doc/whats_new.rst
- mne_connectivity/base.py
- mne_connectivity/tests/test_connectivity.py
- mne_connectivity/tests/test_envelope.py
PR Description
--------------
Adds a default 'compact' option to the get_data() kwarg for backwards compatibility.
> [MRG] Adding compact kwarg to connectivity for backwards compatibility

- mne_connectivity/conftest.py
- mne_connectivity/envelope.py
- mne_connectivity/tests/test_envelope.py
- fix to docstring of `envelope_correlation`, where non-existent param value `orthogonalize='symmetric'` is referred to.
- a few minor code style changes that I noticed along the way
> envelope_correlation docstring fix + minor code style fixes

- .github/workflows/linux_conda.yml
- CONTRIBUTING.md
- README.rst
- doc/authors.inc
- doc/install.rst
- doc/whats_new.rst
- environment.yml
- setup.py
PR Description
--------------
Addresses #78 
> [ENH] Add Conda Installation

- .circleci/config.yml
- azure-pipelines.yml
- doc/authors.inc
- doc/conf.py
- doc/whats_new.rst
- examples/connectivity_classes.py
- examples/cwt_sensor_connectivity.py
- examples/mixed_source_space_connectivity.py
- examples/mne_inverse_label_connectivity.py
- examples/sensor_connectivity.py
- mne_connectivity/base.py
- mne_connectivity/viz/circle.py
- mne_connectivity/viz/tests/test_circle.py
This brings mne-connectivity up to date with changes to connectivity plotting and prevents getting out of sync in the future. Adds a few features from https://github.com/mne-tools/mne-python/pull/10439.
> [ENH, MRG] remove duplicated code, add deprecation for subplot indexing [skip ci

- doc/authors.inc
- doc/whats_new.rst
- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/spectral/time.py
PR Description
--------------
It is the prospective solution of #95 
It fixes the incompatibility of dimensions of frequencies in the creation of EpochSpectroTemporalConnectivity object on line 223 by providing the frequencies of interest into the object, rather than the frequencies used in the time-frequency decomposition. 
Merge Checklist
> Update time.py due to error in spectral_connectivity_time

- .circleci/config.yml
- azure-pipelines.yml
- doc/conf.py
- mne_connectivity/__init__.py
- mne_connectivity/conftest.py
- mne_connectivity/spectral/epochs.py
- tools/circleci_dependencies.sh
- tools/setup_xvfb.sh
@adam2392 we need to remove `_get_args` to comply with 1.2's removal of it. @adam2392 could you merge this if happy and cut a 0.4.0 release?
cc @drammock this one needed an update due to `_get_args`
> MAINT: Update for 1.2 and bump version

- doc/authors.inc
- doc/whats_new.rst
- mne_connectivity/viz/_3d.py
PR Description
--------------
Moved the hard-coded variable n_con to be one of the arguments for the function call. To enable choosing the number of connections shown, instead of always 20. Added a default option, to make it compatible with previous usage.
> [ENH] Added n_con arg to function call

- mne_connectivity/base.py
PR Description
--------------
It's just a simple hint to the function [mne_connectivity.read_connectivity](https://mne.tools/mne-connectivity/stable/generated/mne_connectivity.read_connectivity.html). Fixes #134.
I tried loading the data with all kinds of tools and did not succeed because I was not aware of this function.
> [DOC] Fixes #134. Indicate how to load connectivity data from disk

- doc/whats_new.rst
- mne_connectivity/conftest.py
- mne_connectivity/viz/_3d.py
- mne_connectivity/viz/tests/test_3d.py
Addresses https://mne.discourse.group/t/missing-data-in-3d-connectivity-visualization/7184/4
PR Description
--------------
Exposes new `cmap` argument in `plot_sensors_connectivity`
> Expose colormap in plot_sensors_connectivity

- mne_connectivity/conftest.py
- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/tests/test_connectivity.py
In https://github.com/mne-tools/mne-python/pull/11903 we're trying to make some mne/io stuff private. This changes mne-connectivity to use the explicitly public API
Locally I also had this failure in testing:
```
mne_connectivity/spectral/tests/test_spectral.py:147: in test_spectral_connectivity_parallel
assert repr(con) == repr(read_con)
E   AssertionError: assert '<SpectralCon...3, 9, ~23 kB>' == '<SpectralCon...3, 9, ~22 kB>'
E     Skipping 85 identical leading characters in diff, use -v to show
E     - : 3, 9, ~22 kB>
E     ?           ^
E     + : 3, 9, ~23 kB>
E     ?           ^
```
so this modifies the test to ignore the tiny file size difference
> MAINT: Use explicitly public APIs

- .circleci/config.yml
- .github/workflows/unit_tests.yml
- mne_connectivity/envelope.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/time.py
- mne_connectivity/vector_ar/var.py
- requirements.txt
- requirements_doc.txt
Following [#12121](https://github.com/mne-tools/mne-python/pull/12121) in mne-python, the dev. version of MNE, the behaviour of the `Epochs.get_data()` method has been changed such that in v1.7, a copy of the data will be returned by default (rather than the current view).
Without specifying the `copy` parameter, a `FutureWarning` is raised:
`FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning`
This is causing several of the CI tests to fail when using the MNE dev. version.
Explicitly set `copy=False` in all instances where `Epochs.get_data() is called`. As I understand it the returned data is not modified itself, so returning a view should be sufficient.
**N.B.**: Since the `copy` parameter was added in …
> [MAINT] Fix failing unit tests & update CI packages

- mne_connectivity/spectral/epochs_multivariate.py
- mne_connectivity/spectral/tests/test_spectral.py
A small but notable bug I just came across:
`indices` and `rank` should both have shape `(2, n_cons)`, however if the number of connections differs, e.g.
```
indices = ([[0, 1], [2, 3]],  # 2 seeds
[[4, 5], [6, 7]])  # 2 targets
rank = ([2],  # 1 seed
[2])  # 1 target
```
this does not immediately raise an error. Instead, the use of `zip` elsewhere in the code to iterate over the entries of `indices` and `rank` for each connection means that only the results for the smallest number of connections (in the above example 1 of 2) would be processed.
Example of where `zip` is used:
https://github.com/mne-tools/mne-connectivity/blob/28c3895754626b1ebc6b4dc8523079b52ac8f6b7/mne_connectivity/spectral/epochs_multivariate.py#L185-L186
<br>
Simply adding a check in `_check_rank_input` that the …
> [BUG] Inconsistent lengths of `indices` and `rank` does not raise an error 

- CONTRIBUTING.md
- azure-pipelines.yml
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)
PR Description
--------------
> [CI] Fix azure

- doc/conf.py
- mne_connectivity/conftest.py
- pyproject.toml
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)
PR Description
--------------
> [CI] Fix CIs

- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/spectral/time.py
PR Description
--------------
Make it easier to figure out what went wrong when `spectral_connectivity_time` is passed a Raw instead of Epochs.
https://mne.discourse.group/t/inhomogeneous-shape-error-when-using-mne-connectivity-spectral-connectivity-time/8198
> type-check data input to spectral_connectivity_time

- .github/workflows/unit_tests.yml
- benchmarks/bench_var.py
- benchmarks/single_epoch_conn.py
- pyproject.toml
Codestyle checks are failing due to `benchmarks/bench_var.py` and `benchmarks/single_epoch_conn.py` not being properly formatted. See e.g. #163, #171 for failing checks.
Have now run black on these files to hopefully fix things.
> Fix failing unit tests

- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/time.py
- mne_connectivity/utils/docs.py
Follow up from #170:
- Added newlines before and after methods list in `spectral_connectivity_time()` to ensure it renders properly.
- Added equivalent list to `spectral_connectivity_epochs()`.
- Added definition of individual methods to `docs.py`.
@larsoner Please let me know if the definition of strings in `docs.py` works for you.
Cheers!
> [DOC] Add methods list to `epochs` function and fix formatting of list in `time` function

- mne_connectivity/spectral/epochs_multivariate.py
- mne_connectivity/spectral/time.py
Fix for #174.
In short, the array for storing spatial patterns of connectivity used by the MIC method was unnecessarily being created for all methods. This could lead to memory errors when bivariate connectivity methods were being called on large numbers of connections.
This fix makes it so that the patterns array will only be instantiated in methods that require it, otherwise will be set to `None`. This does not cause any change in behaviour, since for methods where patterns are not used, `None` was already being stored in the `patterns` attribute of the returned connectivity objects.
This is a problem specific to `spectral_connectivity_time()`; `spectral_connectivity_epochs()` was already using the fixed approach.
> [BUG] Fix memory error spectral_connectivity_time

- mne_connectivity/spectral/epochs.py
Suggested fix for #176 where `n_jobs=-1` does not result in CSD computation being properly parallelised over epochs.
This fix makes sure `n_jobs=-1` is converted to the maximum number of workers before CSD computation occurs.
I think also when refactoring some of the multivariate connectivity methods some months ago the `n_jobs` parameter was not being properly passed to the classes. This is also now fixed.
As far as I understand, these issues are specific to `spectral_connectivity_epochs()` and do not affect `spectral_connectivity_time()`.
The current unit tests for parallelisation were only using `n_jobs > 1` and never `n_jobs=-1`. However, even if `n_jobs=-1` was being used this issue would not be caught, as the tests only check that multiple workers can be allocated (which they can) …
> [BUG] n_jobs=-1 not working in spectral_connectivity_epochs

- examples/compare_coherency_methods.py
New codespell version catches a spelling mistake that was previously being missed: "scenarious" which should be "scenarios" in the `compare_coherency_methods.py` example.
> [MAINT] Fix codespell error

- doc/references.bib
- examples/cacoh.py
- examples/compare_coherency_methods.py
- examples/granger_causality.py
- examples/handling_ragged_arrays.py
- examples/mic_mim.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/time.py
Retry of #194 hopefully without line endings messing up diff.
> Was double checking the documentation for mistakes when preparing the v0.7 release and noticed a few grammatical errors, spelling errors missed by codespell, and general poorly-worded parts of my examples.
> 
> There was also a very useful reference for the time-reversal in the Granger causality method which I forgot to include previously.
> 
> I also discovered the wonder of sphinx-gallery in-file config options and specified some nicer thumbnails for these examples.
> [MAINT] Retry improve clarity, thumbnails, and fix mistakes in multivariate examples

- .github/workflows/release.yml
- .yamllint.yml
@larsoner suggested in #181 to modernise publishing to PyPI with trusted artefact publishing on release.
Was suggested to use the MNE-BIDS-Pipeline workflow as a template and removing the username/password stuff: https://github.com/mne-tools/mne-bids-pipeline/blob/main/.github/workflows/release.yml
Haven't touched the existing `publish_release.yml` workflow. Very minor but wasn't sure if we should use this name, rename to `release.yml`, ygm.
Also had to add a new rule to the `.yamllint.yml` config for pre-commit yamllint check to pass on my windows machine due to unix vs. dos line endings.
> [MAINT] Add release workflow

- .pre-commit-config.yaml
- mne_connectivity/base.py
- mne_connectivity/envelope.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/epochs_multivariate.py
- mne_connectivity/spectral/smooth.py
- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/spectral/time.py
- mne_connectivity/tests/test_connectivity.py
- mne_connectivity/utils/docs.py
- mne_connectivity/utils/utils.py
- mne_connectivity/vector_ar/model_selection.py
- mne_connectivity/vector_ar/var.py
- mne_connectivity/viz/_3d.py
- mne_connectivity/viz/circle.py
- mne_connectivity/viz/tests/test_circle.py
Does a few things:
1. Switches to f-string formatting, hopefully didn't miss any (requested by @drammock: https://github.com/mne-tools/mne-connectivity/pull/193#discussion_r1639558215)
2. Gets rid of annoying leftovers from switch to 88 line length where strings that were previously split over two lines no longer are, but were kept as two separate strings, e.g.:
```
"this used to be split over two" "lines" => "this used to be split over two lines"
```
3. Takes advantage of the new 88 line length for strings to reduce code footprint
(2) & (3) weren't requested, I just thought they would be good. If people would rather stick to just (1) I can change this.
> [MAINT] Clean up string formatting

- mne_connectivity/base.py
- mne_connectivity/effective.py
- mne_connectivity/envelope.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/time.py
- mne_connectivity/vector_ar/var.py
Discussed partially in call with @larsoner & @wmvanvliet.
There is a `See Also` section of the docstrings where connectivity functions link to the connectivity containers they return, and the container classes like to the connectivity functions they are returned from. These references were not present everywhere, and I wanted to make them consistent.
However, I found there were existing references where functions were linking to classes they did not return, and classes were linking to functions they were not returned from. There were also cases where the types of container classes returned in connectivity function docstrings were wrong.
There is also an inconsistency where the `Connectivity` class is sometimes used as an indicator of the generic `BaseConnectivity` class, and sometimes …
> [DOC] Update functon-container cross-references and fix incorrect types

- doc/conf.py
- examples/granger_causality.py
- mne_connectivity/utils/docs.py
- pyproject.toml
PR Description
--------------
Something that was discussed a while ago with @larsoner when the Granger causality example was first written but had to be postponed until new config options were added to sphinx-gallery:
- The GC example ends with a `try except` statement that is expected to fail
- It was suggested to remove the `try except` and just allow the error to be raised as long as the example is marked in sphinx as an expected failing example
- The problem was that expected failing examples automatically get a thumbnail with the word "BROKEN" which could not be overridden, and I felt this gave the wrong impression that there was a problem with the whole example
- In the new sphinx-gallery v0.17, support was added allowing this behaviour to be changed such that we can allow the GC …
> [DOC] Switch Granger causality to expected failing example

- mne_connectivity/viz/_3d.py
- mne_connectivity/viz/tests/test_3d.py
PR Description
--------------
Discussed in call with @larsoner.
`plot_sensors_connectivity` expects data to be a 2D (channels x channels) array, however the input shape is never checked. This PR adds such a check and corresponding unit tests.
No similar problem for `plot_connectivity_circle`, as data shape is checked here.
> [MAINT] Add `plot_sensors_connectivity` data shape check

- mne_connectivity/viz/_3d.py
- mne_connectivity/viz/tests/test_3d.py
Addresses #148, discussed in call with @larsoner.
Have gone with options (2) & (3) suggested above. This involves:
- An option to specify the minimum distance required between sensors for a connection to be plotted (default was 5 cm, which has been retained).
- A check that if no connections survive the minimum distance requirement, a more descriptive error message is raised.
- The message suggests increasing the number of connections being plotted or decreasing the minimum distance (would help in cases like https://mne.discourse.group/t/problem-with-different-methods-in-sensor-connectivity-example/7548/4)
- The message also suggests checking that the coordinates of channels are not NaNs (would help in cases like https://mne.discourse.group/t/error-while-trying-to-call-plot-sensors-connect …
> [BUG, ENH] Improve error checking of `plot_sensors_connectivity` and add a `min_distance` parameter

- mne_connectivity/tests/test_envelope.py
- pyproject.toml
cf. https://github.com/mne-tools/mne-python/issues/12789
Locally for me all tests pass except for 3 symmetric_orth runs (2-False, 3-False, and 3-True). **They pass on pytest 7.4.4** so this needs digging into
> unpin pytest

- mne_connectivity/spectral/epochs.py
- pyproject.toml
Creating this PR after brief discussion with @tsbinns. I can also create a formal issue if needed, but for the moment this is a pure documentation PR.
In brief, I was confused by the behavior of ``cwt_freqs``, ``fmin`` and ``fmax``, especially if both ``cwt_freqs`` plus one of the other parameters was specified. Apparently, ``fmin`` and ``fmax`` supersede the ``cwt_freqs`` parameter, which was not evident from the documentation, so I tried to improve the description to make it a bit clearer. I can add more examples, if you think even more detail is needed.
Additionally, I noticed that the parameter ``None`` of ``fmin``, was not documented, even though it is the default, so I added this, too.
I ran make on the docs and they seem to render fine locally. Let me know if you need anything …
> [DOC] Improve documentation of freqs

- examples/decoding/cohy_decomposition_plotting.py
- pyproject.toml
Takes advantage of the new `sphinx_gallery_multi_image` option in v0.18 in the decomposition plotting example to make the filters and patterns easier to see.
Before:
After:
> [DOC] Use `sphinx_gallery_multi_image` in decomposition example

- doc/_static/style.css
- doc/conf.py
- doc/whats_new.rst
- pyproject.toml
PR Description
--------------
use the latest released PyData Sphinx Theme. Main motivation is reduce dev pain (if a dev installs MNE-Connectivity after installing MNE-Python, it will downgrade the theme).
I synced a few parts of `conf.py` and `_static/style.css` with MNE-Python, but stopped short of the primary/secondary color switch from teal-purple to blue-orange like we did on the MNE-Python site. We may want to do that eventually to bring things into "brand alignment" but right now MNE-Connectivity doesn't even have a logo and the teal/purple scheme looks fine, so I left it alone.
> unpin website theme

- mne_connectivity/spectral/epochs.py
Fixes spelling error in documentation for `fmax` param.
> Fix spelling error in `spectral_connectivity_epochs` docstring

- doc/conf.py
- mne_connectivity/base.py
- mne_connectivity/datasets/frequency.py
- mne_connectivity/datasets/surrogate.py
- mne_connectivity/decoding/decomposition.py
- mne_connectivity/effective.py
- mne_connectivity/envelope.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/epochs_multivariate.py
- mne_connectivity/spectral/smooth.py
- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/spectral/time.py
- mne_connectivity/utils/docs.py
- mne_connectivity/utils/utils.py
- mne_connectivity/vector_ar/model_selection.py
- mne_connectivity/vector_ar/tests/test_var.py
- mne_connectivity/vector_ar/var.py
- mne_connectivity/viz/_3d.py
- mne_connectivity/viz/circle.py
Addresses in particular #222 and #282 to fix all ambiguous single backtick entries, either giving them explicit intersphinx roles or making them double backticks like mentioned [here](https://github.com/mne-tools/mne-connectivity/pull/280#discussion_r1932807683).
Also generally brings the docstrings in line with what seem to be more modern MNE principles, including:
- converts the old docstrings to take advantage of the 88 line length.
- uses literals for str params (except in `spec_conn_epochs/time()` `method` param since that has loads of possibilities)
- fixes instances of missing or incorrect types in docstrings.
- changes instances where information could be rendered as code, code blocks, or lists.
- remove `optional` from docstring types and replace with `None`, e.g. `param : type, …
> [DOC] Clean up docstring formatting

- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/epochs_multivariate.py
Fixes #285.
`_tfr_from_mt` now supports ndarray after https://github.com/mne-tools/mne-python/pull/13104. Means we can avoid looping over epochs dimensions when passing in data.
Also fixes a bug from #232 where `_tfr_from_mt` would be imported even when not required, making everything incompatible with MNE<1.10. Now it is only imported when required.
> Change calls to `_tfr_from_mt` with support for ndarrays

- .github/workflows/unit_tests.yml
Suggested by @larsoner. Currently only run unit tests on `mne-main` which can lead to bugs slipping through (e.g. #286).
This adds a test for the stable MNE version on Ubuntu. Should it be tested on more platforms like in [MNE-BIDS](https://github.com/mne-tools/mne-bids/blob/4f12d190d19a201a5b74fa1c8aaedac4d87775c8/.github/workflows/unit_tests.yml#L145-L147)?
Also updates the latest Python version tested from 3.12 to 3.13.
> [MAINT] Run CIs on MNE-stable and update to latest Python version

- .pre-commit-config.yaml
- doc/whats_new.rst
- mne_connectivity/base.py
- mne_connectivity/envelope.py
- mne_connectivity/spectral/epochs.py
- mne_connectivity/spectral/tests/test_spectral.py
- mne_connectivity/spectral/time.py
- mne_connectivity/tests/test_envelope.py
- mne_connectivity/vector_ar/tests/test_var.py
- mne_connectivity/vector_ar/var.py
PR Description
--------------
Fixes #323.
When `indices=None` (`spec_conn_epochs/time`, `phase_slope_index`) or when no `indices`  parameter is supported (`envelope_correlation`, `vector_auto_regression`), bad channels are now ignored from connectivity computations.
However, entries for these bad channels will still be considered in the dense representation of the matrices as per this discussion: https://github.com/mne-tools/mne-connectivity/issues/323#issuecomment-3286402064
> [BUG] Fix including bad channels in computations
